on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⚡ Run tests
        run: |
          deno test --allow-env --allow-net --unstable src/*.test.ts

      - name: 📥 Generate npm package
        run: |
          deno run -A scripts/build-npm.ts 1.0.0
